### ISSUE TITLE
Error when enabling pling 1.19.4

### ISSUE THREAD

**Issue by Hyperbean18** [haykam821/Pling#10]
Hello, Im getting the following crash log when trying to use pling on 1.19.4, not sure whats going wrong or where there is a conflict

[https://paste.ee/p/hUbNO](https://paste.ee/p/hUbNO)

**Comment by R00tB33rMan** [comment]
Issue appears to be caused by MemoryLeakFix. Believe it is an issue that MemoryLeakFix needs to resolve but either resource can resolve this conflict.

**Comment by haykam821** [comment]
Relates to fxmorin/MemoryLeakFix#105

**Comment by Calamity2112** [comment]
Also getting a crash on 1.19.4, unrelated to memory leak fix as I don't use it. Game launches fine, but crashes as soon as I attempt to enter the single player menu. Using Quilt 0.18.10 on Prism Launcher 6.3

Crash Log: https://mclo.gs/elV2YCZ

**Comment by VeggeieDude** [comment]
Same, I also get this crash without memory leak fix installed

**Comment by haykam821** [comment]
If you are having issues without Memory Leak Fix, do you have any other mods installed that may cause compatibility issues?

**Comment by haykam821** [comment]
The issue seems to be that Pling is incompatible with Minecraft 1.19.4 in some areas, namely creating worlds. Memory Leak Fix simply causes the issue to always happen instead of only if the create world screen is opened. 8081e55a1293941103d22fdd1725ddc0f3eaac93 fixes the mixin issues.

**Comment by R00tB33rMan** [comment]
Tested a few days ago and latest build works with MemoryLeakFix plus is fully 1.19.4 compatible. Make sure Gradle 8.1+ is used when compiling, since it fails to compile on Gradle 8.0.

**Comment by haykam821** [comment]
[Version 1.7.0](https://github.com/haykam821/Pling/releases/tag/1.7.0) supports Minecraft 1.19.4.
